from enum import StrEnum


class AgentStatus(StrEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class GrantStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"


class QuoteStatus(StrEnum):
    OPEN = "OPEN"
    CONSUMED = "CONSUMED"
    EXPIRED = "EXPIRED"


class PaymentMode(StrEnum):
    RAZORPAY_PAYMENT_LAB = "RAZORPAY_PAYMENT_LAB"
    DELEGATED_DEBIT_SIMULATOR = "DELEGATED_DEBIT_SIMULATOR"


class CheckoutStatus(StrEnum):
    CANCEL_WINDOW = "CANCEL_WINDOW"
    ORDER_CREATING = "ORDER_CREATING"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    EXPIRING = "EXPIRING"
    RECONCILING = "RECONCILING"
    PAID = "PAID"
    SIMULATED_SETTLED = "SIMULATED_SETTLED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    FAILED_TERMINAL = "FAILED_TERMINAL"
    LATE_CAPTURE_INCIDENT = "LATE_CAPTURE_INCIDENT"


class ReservationStatus(StrEnum):
    HELD = "HELD"
    CONSUMED = "CONSUMED"
    RELEASED = "RELEASED"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    PROPOSAL_READY = "PROPOSAL_READY"
    CHECKOUT_SCHEDULED = "CHECKOUT_SCHEDULED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class WebhookStatus(StrEnum):
    RECEIVED = "RECEIVED"
    PROCESSED = "PROCESSED"
    IGNORED = "IGNORED"
    FAILED = "FAILED"
